[program:new4dgs-training]
environment=PROC_NAME="new4dgs-training"
command=/opt/supervisor-scripts/new4dgs-training.sh
autostart=false
autorestart=false
startsecs=5
stopasgroup=true
killasgroup=true
stopsignal=TERM
stopwaitsecs=30
stdout_logfile=/dev/stdout
redirect_stderr=true
stdout_logfile_maxbytes=0
